### ISSUE TITLE
Support for SLAB out of process service

### ISSUE THREAD

**Issue by bkaid** [DeHeerSoftware/SemanticLogging.EventHub#1]
In order to support the [Semantic Logging Out Of Process Service](https://github.com/mspnp/semantic-logging/tree/master/source/Src/SemanticLogging.Etw.WindowsService), a different namespace needs to be set on the configuration element's sink name instead of using the framework's namespace:

` private readonly XName sinkName = XName.Get("eventHubHttpSink", Constants.Namespace);`

Re-using their namespace causes the following error: 

*The element 'sinks' in namespace 'http://schemas.microsoft.com/practices/2013/entlib/semanticlogging/etw' has invalid child element 'eventHubHttpSink' in namespace 'http://schemas.microsoft.com/practices/2013/entlib/semanticlogging/etw'. List of possible elements expected: 'flatFileSink, rollingFlatFileSink, windowsAzureTableSink, sqlDatabaseSink, consoleSink, customSink' in namespace 'http://schemas.microsoft.com/practices/2013/entlib/semanticlogging/etw' as well as any element in namespace '##other'.*

Also, a sample configuration entry on the readme page would be helpful.  Something like:
`<eventHubHttpSink xmlns="https://github.com/DeHeerSoftware/SemanticLogging.EventHub" name="eventHubHttpSink" eventHubNamespace="your-namespace" eventHubName="your-event-hub-name">
      <etw:sources>
        <etw:eventSource name="your-event-source-name" level="Verbose"  />
      </etw:sources>
    </eventHubHttpSink>`

**Comment by Expecho** [comment]
Hi @bkaid 

Thanks for noticing. I have updated the readme file. Is it enough to help you out?

**Comment by bkaid** [comment]
The updated namespace and readme worked out great. Thanks!
